version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-demo-app

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: ec2-user
